# Generated by Django 3.2.8 on 2021-10-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('day', models.CharField(max_length=20)),
                ('hour', models.CharField(max_length=20)),
                ('dayOfMonth', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('dayOfWeek', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('script', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedAt', models.DateTimeField()),
                ('finishedAt', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('crontab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.crontab')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.scripts')),
            ],
        ),
        migrations.AddField(
            model_name='crontab',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.scripts'),
        ),
    ]
