# Generated by Django 3.2.8 on 2021-11-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_executionmanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='crontab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.crontab'),
        ),
    ]
