# Generated by Django 3.2.8 on 2021-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_executionlog_crontab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionmanual',
            name='finishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
