# Generated by Django 3.2 on 2021-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20211123_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='startedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
