# Generated by Django 3.2 on 2021-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_executionlog_startedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
