# Generated by Django 3.2 on 2021-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_executionlog_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontab',
            name='arguments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionmanual',
            name='arguments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
